### ISSUE TITLE
Integrating HEAD Plugin 

### ISSUE THREAD

**Issue by goelprateek** [Jaraxal/ambari-elasticsearch-service#1]
Hi ,

I am new to ambari services , can u please guide me in integrating plugins using ambari web UI .

**Comment by Jaraxal** [comment]
@goelprateek 

You can easily add plugins to Elasticsearch by updating the configuration section of the master.py script.  I'm working on updating the service to add HQ and HEAD plugins.

Right now the HQ plugin does is not supported for ES 5.x.  The HEAD plugin isn't support for ES 5.x as a plugin; you have to run it as a standalone server.

**Comment by Jaraxal** [comment]
I have updated the service definition to install the X-Pack plugin automatically.  X-Pack security is disabled by default by adding xpack.security.enabled: false to the elasticsearch.yml configuration file.

**Comment by goelprateek** [comment]
Hi Jaraxal,

Thanx for reply, I will look into it.
